### ISSUE TITLE
搜尋功能-找尋到hashtag的關鍵字

### ISSUE THREAD

**Issue by michaeljordan1963** [weitingchou/toppano.com#28] opened 2016-06-23 06:02 UTC
例如:找#verpix
<img width="1249" alt="2016-06-23 1 58 22" src="https://cloud.githubusercontent.com/assets/20082135/16293228/c526d01e-394a-11e6-8edf-eac73c36301d.png">

就會列出所有有下過#verpix的照片
<img width="1233" alt="2016-06-23 1 58 49" src="https://cloud.githubusercontent.com/assets/20082135/16293245/ec7b30b0-394a-11e6-80d7-0949c3f8d05d.png">

**Comment by weitingchou** [comment] 2016-06-23 06:50
Duplicate of issue #15

**Closed as completed by weitingchou** 2016-06-23 06:50 UTC
Labels: duplicate, idea
